apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  namespace: devops-ns
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      # volumes:
      #   - name: devops-data
      #     persistentVolumeClaim:
      #       claimName: devops-data
      containers:
      - name: devops-container
        image: iamthemoon/devsecops-box:latest

        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        # volumeMounts:
        #   - name: devops-data
        #     mountPath: /data/db
        #     subPath: appdata
        #   - name: devops-data
        #     mountPath: /etc/devops
        #     subPath: etcconfig

        ports:
          - containerPort: 80
            name: devops
            protocol: TCP
